DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS goals CASCADE;

CREATE TABLE users(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE goals(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  goalAmount TEXT NOT NULL,
  currentAmount INTEGER NOT NULL, 
  user_id BIGINT REFERENCES users(id) NOT NULL
);