DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS goals CASCADE;

CREATE TABLE users(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE goals(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  goal_amount INTEGER NOT NULL,
  current_amount INTEGER NOT NULL, 
  private_state BOOLEAN NOT NULL,
  completed BOOLEAN NOT NULL,
  date_created VARCHAR(50) NOT NULL,
  user_id BIGINT REFERENCES users(id) NOT NULL
);